services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${db_login}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${db_name}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_db/pgdata/:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${db_login} -d ${db_name}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - '8989:8989'
    environment:
      DATABASE_URL: postgresql+asyncpg://${db_login}:${db_password}@postgres:5432/${db_name}
      DB_LOGIN: ${db_login}
      DB_PASSWORD: ${db_password}
      DB_NAME: ${db_name}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
