"""change model User

Revision ID: 0da3db43ec65
Revises: e7cf4def8ee0
Create Date: 2026-06-09 21:47:06.801889

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0da3db43ec65"
down_revision: Union[str, Sequence[str], None] = "e7cf4def8ee0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "role", existing_type=sa.VARCHAR(length=20), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "role", existing_type=sa.VARCHAR(length=20), nullable=True)
    # ### end Alembic commands ###
