"""correction table users

Revision ID: 0ee71c0bf43b
Revises: 4b2b58f81fce
Create Date: 2026-06-12 18:30:08.652166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ee71c0bf43b"
down_revision: Union[str, Sequence[str], None] = "4b2b58f81fce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    # ### end Alembic commands ###
