"""change field login to username

Revision ID: e7cf4def8ee0
Revises: ad37ae1e3ebf
Create Date: 2026-06-07 20:00:24.904878

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7cf4def8ee0"
down_revision: Union[str, Sequence[str], None] = "ad37ae1e3ebf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("username", sa.String(length=20), nullable=False))
    op.drop_constraint(op.f("user_login_key"), "user", type_="unique")
    op.create_unique_constraint(None, "user", ["username"])
    op.drop_column("user", "login")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("login", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "user", type_="unique")
    op.create_unique_constraint(
        op.f("user_login_key"), "user", ["login"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("user", "username")
    # ### end Alembic commands ###
